export const GET_PREVIOUS_SELECTED_YEAR_REQUEST =
  "GET_PREVIOUS_SELECTED_YEAR_REQUEST";
export const GET_PREVIOUS_SELECTED_YEAR_SUCCESS =
  "GET_PREVIOUS_SELECTED_YEAR_SUCCESS";
export const GET_PREVIOUS_SELECTED_YEAR_FAIL =
  "GET_PREVIOUS_SELECTED_YEAR_FAIL";

export const CUSTOM_DATA_SELECTOR_REQUEST = "CUSTOM_DATA_SELECTOR_REQUEST";
export const CUSTOM_DATA_SELECTOR_SUCCESS = "CUSTOM_DATA_SELECTOR_SUCCESS";
export const CUSTOM_DATA_SELECTOR_FAIL = "CUSTOM_DATA_SELECTOR_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
