export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_FAIL = "CREATE_CUSTOMER_FAIL";

export const GET_ALL_CUSTOMER_REQUEST = "GET_ALL_CUSTOMER_REQUEST";
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER_FAIL = "GET_ALL_CUSTOMER_FAIL";

export const SINGLE_CUSTOMER_REQUEST = "SINGLE_CUSTOMER_REQUEST";
export const SINGLE_CUSTOMER_SUCCESS = "SINGLE_CUSTOMER_SUCCESS";
export const SINGLE_CUSTOMER_FAIL = "SINGLE_CUSTOMER_FAIL";

export const UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";

export const SET_CUSTOMER_ACTIVE_OR_INACTIVE_REQUEST =
  "SET_CUSTOMER_ACTIVE_OR_INACTIVE_REQUEST";
export const SET_CUSTOMER_ACTIVE_OR_INACTIVE_SUCESS =
  "SET_CUSTOMER_ACTIVE_OR_INACTIVE_SUCESS";
export const SET_CUSTOMER_ACTIVE_OR_INACTIVE_FAIL =
  "SET_CUSTOMER_ACTIVE_OR_INACTIVE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
