export const GET_FAT_RATE_REQUEST = "GET_FAT_RATE_REQUEST";
export const GET_FAT_RATE_SUCCESS = "GET_FAT_RATE_SUCCESS";
export const GET_FAT_RATE_FAIL = "GET_FAT_RATE_FAIL";

export const UPDATE_FAT_RATE_REQUEST = "UPDATE_FAT_RATE_REQUEST";
export const UPDATE_FAT_RATE_SUCCESS = "UPDATE_FAT_RATE_SUCCESS";
export const UPDATE_FAT_RATE_FAIL = "UPDATE_FAT_RATE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
