export const GET_LOCKED_DATE_REQUEST = "GET_LOCKED_DATE_REQUEST";
export const GET_LOCKED_DATE_SUCCESS = "GET_LOCKED_DATE_SUCCESS";
export const GET_LOCKED_DATE_FAIL = "GET_LOCKED_DATE_FAIL";

export const GET_UPDATED_LOCKED_DATE_REQUEST =
  "GET_UPDATED_LOCKED_DATE_REQUEST";
export const GET_UPDATED_LOCKED_DATE_SUCCESS =
  "GET_UPDATED_LOCKED_DATE_SUCCESS";
export const GET_UPDATED_LOCKED_DATE_FAIL = "GET_UPDATED_LOCKED_DATE_FAIL";

export const GET_LOCK_STATE_REQUEST = "GET_LOCK_STATE_REQUEST";
export const GET_LOCK_STATE_SUCCESS = "GET_LOCK_STATE_SUCCESS";
export const GET_LOCK_STATE_FAIL = "GET_LOCK_STATE_FAIL";

export const TOGGLE_LOCK_REQUEST = "TOGGLE_LOCK_REQUEST";
export const TOGGLE_LOCK_SUCCESS = "TOGGLE_LOCK_SUCCESS";
export const TOGGLE_LOCK_FAIL = "TOGGLE_LOCK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
