export const DELETE_PURCHASE_REQUEST = "DELETE_PURCHASE_REQUEST";
export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS";
export const DELETE_PURCHASE_FAIL = "DELETE_PURCHASE_FAIL";

export const CREATE_PURCHASE_REQUEST = "CREATE_PURCHASE_REQUEST";
export const CREATE_PURCHASE_SUCCESS = "CREATE_PURCHASE_SUCCESS";
export const CREATE_PURCHASE_FAIL = "CREATE_PURCHASE_FAIL";

export const GET_LATEST_PURCHASE_SERIAL_REQUEST =
  "GET_LATEST_PURCHASE_SERIAL_REQUEST";
export const GET_LATEST_PURCHASE_SERIAL_SUCCESS =
  "GET_LATEST_PURCHASE_SERIAL_SUCCESS";
export const GET_LATEST_PURCHASE_SERIAL_FAIL =
  "GET_LATEST_PURCHASE_SERIAL_FAIL";

export const ALL_PURCHASE_REQUEST = "ALL_PURCHASE_REQUEST";
export const ALL_PURCHASE_SUCCESS = "ALL_PURCHASE_SUCCESS";
export const ALL_PURCHASE_FAIL = "ALL_PURCHASE_FAIL";

export const SINGLE_PURCHASE_REQUEST = "SINGLE_PURCHASE_REQUEST";
export const SINGLE_PURCHASE_SUCCESS = "SINGLE_PURCHASE_SUCCESS";
export const SINGLE_PURCHASE_FAIL = "SINGLE_PURCHASE_FAIL";

export const UPDATE_PURCHASE_REQUEST = "UPDATE_PURCHASE_REQUEST";
export const UPDATE_PURCHASE_SUCCESS = "UPDATE_PURCHASE_SUCCESS";
export const UPDATE_PURCHASE_FAIL = "UPDATE_PURCHASE_FAIL";

export const WEEK_WISE_PURCHASE_REQUEST = "WEEK_WISE_PURCHASE_REQUEST";
export const WEEK_WISE_PURCHASE_SUCCESS = "WEEK_WISE_PURCHASE_SUCCESS";
export const WEEK_WISE_PURCHASE_FAIL = "WEEK_WISE_PURCHASE_FAIL";

export const CUSTOMER_WISE_PURCHASE_REQUEST = "CUSTOMER_WISE_PURCHASE_REQUEST";
export const CUSTOMER_WISE_PURCHASE_SUCCESS = "CUSTOMER_WISE_PURCHASE_SUCCESS";
export const CUSTOMER_WISE_PURCHASE_FAIL = "CUSTOMER_WISE_PURCHASE_FAIL";

export const CUSTOMER_WISE_PURCHASE_OUTLIERS_REQUEST =
  "CUSTOMER_WISE_PURCHASE_OUTLIERS_REQUEST";
export const CUSTOMER_WISE_PURCHASE_OUTLIERS_SUCCESS =
  "CUSTOMER_WISE_PURCHASE_OUTLIERS_SUCCESS";
export const CUSTOMER_WISE_PURCHASE_OUTLIERS_FAIL =
  "CUSTOMER_WISE_PURCHASE_OUTLIERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
